variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIVADO_PATH_SH: '/nfs/data41/software/Xilinx/Vivado/${VIVADO_VERSION}/settings64.sh'
  CLANG_TIDY_PATH: '/opt/rh/llvm-toolset-7/root/bin/clang-tidy'
  CLANG_TIDY_OPTIONS: '-format-style=file' #-config='' does not work because of the quotes; -header-filter in .clang-tidy
  CLANG_TIDY_COMP_OPTIONS: '-std=c++11 -I../TrackletAlgorithm -I../TestBenches -I/nfs/data41/software/Xilinx/Vivado/2019.2/include'

stages: # ---------------------------------------------------------------------
#  - quality-check
  - hls-build
  - topTF-build

# Job templates ---------------------------------------------------------------
.job_template: &template_base
  tags:
    - xilinx-tools
  before_script:
    - source $VIVADO_PATH_SH

.job_template: &template_quality-check
  tags:
    - xilinx-tools
  stage: quality-check
  script:
    - cd emData
    - ./download.sh
    - cd ../project
    - pwd; ls -la; #debug
    # Hard coded -config='' because the quotes do not work in the variable
    - ${CLANG_TIDY_PATH} -config='' ${CLANG_TIDY_OPTIONS} ${CLANG_TIDY_FILES} -- ${CLANG_TIDY_COMP_OPTIONS} ${CLANG_TIDY_INCLUDES}
  allow_failure: true # to proceed with errors for now

.job_template: &template_hls-build
  <<: *template_base
  stage: hls-build
  script:
    - cd project
    - pwd; ls -la; #debug
    - vivado_hls -f "script_${PROJ_NAME}.tcl"
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./project/
      - ./emData/
    expire_in: 1 week

.job_template: &template_topTF-build
  <<: *template_base
  stage: topTF-build
  script:
    - cd IntegrationTests/ExpTopPRMEMC_Test
    - pwd; ls -la; #debug
    - vivado -mode tcl -source generate_project.tcl
    - vivado -mode tcl -source synth.tcl
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./IntegrationTests/ExpTopPRMEMC_Test/*.txt
      - ./IntegrationTests/ExpTopPRMEMC_Test/ExpTopPRMEMC_Test/ExpTopPRMEMC_Test.runs/synth_1/*.rpt
    expire_in: 1 week
# Jobs ------------------------------------------------------------------------
# HLS builds ---------------
PR-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "PR"
ME-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "ME"
MC-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "MC"
topPRMEMC-build:
  <<: *template_topTF-build
  variables:
    VIVADO_VERSION: "2019.2"
